config/routes.rb
Rails.application.routes.draw do
  resources :user_mailer_autos, :user

  resources :interviews do
    resources :interview_slots
  end

  root 'welcome#index'
  get 'welcome/index'
  get 'index' => 'welcome#index'
  get 'welcome/register'
  get 'register' => 'welcome#register'
  get 'welcome/about'
  get 'about' => 'welcome#about'
  get 'welcome/schedule'
  get 'schedule' => 'interviews#new'
  post 'welcome/schedule' => 'welcome#schedule'
  post 'interviews/new' => 'interviews#create'

  get 'show' => 'interviews#show'
  get 'interview/cancel' => 'interviews#cancel'
  post 'interview/cancel' => 'interviews#cancel'
  resources :interview_slots

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController

  attr_accessor(:interview_slots)
  attr_accessor(:user)

  def index
    raise ActionController::RoutingError.new('Not Found') unless params[:password] == "whateveryouwant"
    @interviews = Interview.all
  end

  def show
    raise ActionController::RoutingError.new('Not Found') unless params[:password] == "whateveryouwant"
    @interview = Interview.find_by(id: params[:id])
    if @interview.nil?
      @interview = Interview.all
      flash.now[:alert] = "Interview not found"
     redirect_to schedule_path
    end
    redirect_to schedule_path
  end

  def new
    @interview = Interview.new
  end

  def create
    @interview = Interview.create(interview_parameters)
    @interview_slot = InterviewSlot.find(interview_slots_parameters[:interview_id])
    @interview_slot.update_attributes( interview_slots_parameters[:interview_time_slot].to_sym=> "Booked", interview_slots_parameters[:interviewID].to_sym=> interview_slots_parameters[:interview_id])

    if @interview_slot.save! and @interview.save
      redirect_to interviews_new_path
      UserMailer.welcome_email(@interview).deliver_now
    else
      flash.now[:alert] = "Slot has already been Booked!"
    end
    session.clear
  end

  def edit
    @interview = Interview.find(params[:id])
  end

  def update
    @interview = Interview.find(params[:id])
    @interview.update(interview_parameters)

    redirect_to interviews_new_path
  end

  def destroy

    @interview = Interview.find_by(id: params[:id])
    @interview_slot = InterviewSlot.find(@interview.slotID)
    @interview_slot.update_attribute(@interview.slotTimeDescription.to_sym, "Available")
    @interview.destroy
    redirect_to interviews_new_path

  end

  def cancel
    @interview = Interview.find_by(:email=> params[:interview][:email])
    @interview_slot = InterviewSlot.find(@interview.slotID)
    @interview_slot.update_attribute(@interview.slotTimeDescription.to_sym, "Available")
    @interview.destroy
    redirect_to interviews_new_path
  end

  def cancelInterview
    @interview = @interviews.find_by(:email=> params[:interview][:email])
  end

  private
  def interview_parameters
    params.require(:interview).permit(:name, :lastName, :email, :phoneNumber, :interviewTime, :interviewField,
                                      :interviewStatus, :slotTimeDescription, :slotID, :cancelEmail)
  end

  def interview_slots_parameters
    params.require(:interview_slot).permit(:interview_id, :interview_time_slot, :interviewID)
  end
end

app/helpers/interview_helper.rb
module InterviewHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_cancel_form.erb
<%= form_for :interview, url: cancel_interview_path do |f| %>
  <div id="cancelFormWrapper">
    <!-- Popup Div Starts Here -->
    <div id="popupCancelForm">
      <div id="cancelform">
        <!-- Contact Us Form -->
        <%=image_tag("close_icon.jpg", :onclick =>"div_hide()", :class =>"close_icon" )%>
        <h2 style="background-color: cornflowerblue">Enter Your Email Below.</h2>
        <hr>
        <%= f.text_field :email, :id => 'email', :placeholder =>'Email' %>
        <%= f.submit  :id=> 'cancelFormSubmit' %>

      </div>
    </div>
    <!-- Popup Div Ends Here -->
  </div>

<% end %>

app/views/interviews/_new.html.erb
<!--<script type='text/javascript' src="form.js.erb"></script>-->

<html>
    <% content_for :head do %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <% page_heading "Atlanta / Schedule a Mock Interview" %>
        <meta name="description" content="Hey Atlanta, come participate in CareerBuilder’s Mock Interview Day.  Space is limited.  Register here." />
    <% end %>
    <div>
      <div id="header">
        <h4>Next Mock Interview Day: September 17, 2016</h4>
      </div>
      <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Daya", class:"respimg")%>
    </div>
    <section>
      <h2>Schedule Your Mock Interview Here</h2>

      <%= render 'interview_slots/index' %>

      <%= form_for :interview, url: new_interview_path do |f| %>
          <div id="abc">
            <!-- Popup Div Starts Here -->
            <div id="popupContact">
              <div id="abcform">
                <!-- Contact Us Form -->
                <%=image_tag("close_icon.jpg", :onclick =>"div_hide()", :class =>"close_icon" )%>
                <h2 style="background-color: cornflowerblue">Enter Your Information</h2>
                <hr>
                <%= f.hidden_field( :interviewField, :id=> 'interviewField') %>
                <%= f.hidden_field( :interviewTime, :id => 'interviewTime') %>
                <%= f.hidden_field( :slotTimeDescription, :id=> 'slotTimeDescription') %>
                <%= f.hidden_field( :interviewStatus, :id => 'interviewstatus', :value => "Available") %>
                <%= f.hidden_field( :slotID, :id => 'slotID') %>
                <%= f.text_field :name, :id => 'first_Name', :placeholder =>'Name'  %>
                <%= f.text_field :lastName, :id => 'last_Name', :placeholder =>'Last Name' %>
                <%= f.text_field :email, :id => 'email', :placeholder =>'Email' %>
                <%= f.text_field :phoneNumber, :id => 'phoneNumber',:placeholder =>'Phone Number'  %>
                <%#= f.text_area :message, :id => 'message', :placeholder =>'Tell us about You!'  %>

                <%= fields_for :interview_slot do |i| %>
                    <%= i.hidden_field( :interviewID, :id=> 'interviewID', :value => "interview_id") %>
                    <%= i.hidden_field( :interview_id, :id=> 'interview_id') %>
                    <%= i.hidden_field( :interview_time_slot, :id=> 'interviewTimeSlot') %>
                <% end %>

                <%= f.submit  :id=> 'cmdsend' %>

              </div>
            </div>
            <!-- Popup Div Ends Here -->
          </div>

      <% end %>
      <input id="bookedr" type="hidden" value="">
      <input id="bookedc" type="hidden" value="">
      </br></br></br>
      <ul class="body_text"><span style="font-weight: 700; color:#000000">How to Register for a Mock Interview</span>
        <ul>
          <li>Click on an available time slot for the type of job opening for which you would like to be interviewed for</li>
          <li>Fill out the pop-up registration form and click “Submit” once you’re done (Note: You may need to enable
                        pop-ups on your browser).
          </li>
          <li>You will receive a confirmation email within about an hour. The email will confirm your registration time
              as well as provide instructions on what to bring, how to dress, etc.
          </li>
        </ul>
      </ul>

      <br>
      <br>
      <address>
        <strong>For More Information Email</strong><br>
        <a href="mailto:cbmid@cb.com">cbmid@cb.com</a>
      </address>
    </section>
</html>

app/views/interviews/cancel.html.erb
html>
<% content_for :head do %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" xmlns="http://www.w3.org/1999/html">
    <% page_heading "Atlanta / Schedule a Mock Interview" %>
    <meta name="description" content="Hey Atlanta, come participate in CareerBuilder’s Mock Interview Day.  Space is limited.  Register here." />
<% end %>
<div>
  <div id="header">
    <h4>Next Mock Interview Day: September 17, 2016</h4>
  </div>
  <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Daya", class:"respimg")%>
</div>
</html>

app/views/interviews/edit.html.erb
<div>
  <h1> Editing Interviewees </h1>
  <div class="editBox">
    <%= form_for :interview, url: interview_path(@interview), method: :patch do |f| %>

    <%= f.label :Name %>
    <%= f.text_field :name %> <br>

    <%= f.label :LastName %>
    <%= f.text_field :lastName %> <br>

    <%= f.label :Email %>
    <%= f.text_field :email %> <br>

    <%= f.label :PhoneNumber %>
    <%= f.text_field :phoneNumber %> <br>

    <%= f.label :InterviewField %>
    <%= f.text_field :interviewField %> <br>

    <%= f.label :InterviewTime %>
    <%= f.text_field :interviewTime %> <br>

    <%= f.label :InterviewStatus %>
    <%= f.text_field :interviewStatus %> <br>
    <div class="subbutton">
      <%= f.submit 'Save Information'%>
    </div>

    <div class="mainlinks">
      <%= link_to 'Back to list of interviews', interviews_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/interviews/index.html.erb
<html>
<head></head>

<body>
<table>
  <tr>
    <th>Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Interview Time</th>
    <th>Interviewing Department</th>
  </tr>
  <%  @interviews.each do |interview| %>
      <tr>
        <td><%= link_to( interview.name, edit_interview_path(interview)) %></td>
        <td><%= interview.lastName %></td>
        <td><%= interview.email %></td>
        <td><%= interview.phoneNumber%></td>
        <td><%= interview.interviewTime%></td>
        <td><%= interview.interviewField%></td>
        <td><%= link_to 'Delete Record', interview_path(interview), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <%end%>
</table>


</body>
</html>

app/views/interviews/new.html.erb
<%= render 'new' %>

app/views/interviews/show.html.erb
<h1>Interview#show</h1>
<p>Find me in app/views/interview/show.html.erb</p>
<p>
  <strong>Name:</strong>
  <%= @interview.name %><br>
  <strong>Last Name</strong>
  <%= @interview.lastName  %><br>
  <strong>Interview Status</strong>
  <%= @interview.interviewStatus %>
</p>