config/routes.rb
Rails.application.routes.draw do
  resources :user_mailer_autos, :user

  resources :interviews do
    resources :interview_slots
  end

  root 'welcome#index'
  get 'welcome/index'
  get 'index' => 'welcome#index'
  get 'welcome/register'
  get 'register' => 'welcome#register'
  get 'welcome/about'
  get 'about' => 'welcome#about'
  get 'welcome/schedule'
  get 'schedule' => 'interviews#new'
  post 'welcome/schedule' => 'welcome#schedule'
  post 'interviews/new' => 'interviews#create'

  get 'show' => 'interviews#show'
  get 'interview/cancel' => 'interviews#cancel'
  post 'interview/cancel' => 'interviews#cancel'
  resources :interview_slots

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @interview_slots = InterviewSlot.all
  end

  #def new
  # end



  def show
    @interview_slots = InterviewSlot.all
  end

  def register
  end

  def about
  end

  def schedule
    @interview_slots = InterviewSlot.all
    #@interview_slot = InterviewSlot.new
    #@interview_slot.save
  end
  def new
    #@interview_slot = InterviewSlot.new
    #@interview_slot.save
    #redirect_to(:action => 'update')

  end

  def create
    # @interview_slot = InterviewSlot.new(interview_slots_parameters)
    # @interview_slot.save
  end

  private
  def interview_slots_parameters
    params.require( :interview_slot ).permit( :jobType, :nineAM, :nine30AM,
                                              :tenAM, :ten30AM, :elevenAM,
                                              :eleven30AM, :NOON, :twelve30PM, :onePM )
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_form.html.erb
<script type='text/javascript' src="form.js.erb"></script>

<!html>

<table id="scheduler">
    <tr class="tableheader">
      <td style="text-align: left">Job Opening Type </td>
      <td>9:00 AM</td>
      <td>9:30 AM</td>
      <td>10:00 AM</td>
      <td>10:30 AM</td>
      <td>11:00 AM</td>
      <td>11:30 AM</td>
      <td>12:00 Noon</td>
      <td>12:30 PM</td>
      <td>1:00 PM</td>
    </tr>
    <tr>
      <td class="JobCategory">Sales</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
      <td class="Status">Available</td>
    </tr>
  <tr>
    <td class="JobCategory">Sales</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">Technology</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">Technology</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
  <tr>
    <td class="JobCategory">General</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
    <td class="Status">Available</td>
  </tr>
</table>

<%= form_for :interview, url: interview_show_path do |f| %>
<div id="abc">
  <!-- Popup Div Starts Here -->
  <div id="popupContact">
    <div id="abcform">
    <!-- Contact Us Form -->
      <img id="close" src="../../images/close_icon.jpg" onclick ="div_hide()">
      <h2>Enter Your Information</h2>
      <hr>
      <%= f.text_field :name, :id =>'name', :placeholder =>"Name"  %>
      <%= f.text_field :lastName, :placeholder =>"Last Name", :id => 'lastName' %>
      <%= f.text_field :email, :placeholder =>"Email", :id => 'email' %>
      <%= f.text_field :phoneNumber, :placeholder =>"Phone Number", :id => 'phoneNumber' %>
      <%= f.text_area :message, :placeholder =>"Tell us about You!", :id => 'message' %>
      <%= f.hidden_field :interviewField, :id => 'interviewField' %>
      <%= f.hidden_field :interviewTime, :id => 'interviewTime' %>
      <%= f.submit  :id=> 'cmdsend'  %>
     <!-- <input id="name" name="name" placeholder="Name" type="text">
      <input id="lastName" name="lastName" placeholder="Last Name" type="text">
      <input id="email" name="email" placeholder="Email" type="text">
      <input id="phoneNumber" name="phoneNumber" placeholder="phone Number" type="text">
      <textarea id="msg" name="message" placeholder="Tell Us About You!"></textarea>
      <a href="#" id="cmdsend">Send</a> -->
  </div></div>
  <!-- Popup Div Ends Here -->
</div>
<% end %>
<input id="bookedr" type="hidden" value="">
<input id="bookedc" type="hidden" value="">



</html>

app/views/welcome/_interviewform.html.erb
<script type='text/javascript' src="form.js.erb"></script>

<!html>

<%= form_for :interview do |f| %>
    <div id="abc">

  <!-- Popup Div Starts Here -->
  <div id="popupContact">
    <div id="abcform">
      <!-- Contact Us Form -->
      <img id="close" src="../../images/close_icon.jpg" onclick ="div_hide()">
      <h2>Enter Your Information</h2>
      <hr>

      <input id="name" name="name" placeholder="Name" type="text">
      <input id="lastName" name="lastName" placeholder="Last Name" type="text">
      <input id="email" name="email" placeholder="Email" type="text">
      <input id="phoneNumber" name="phoneNumber" placeholder="phone Number" type="text">
      <textarea id="msg" name="message" placeholder="Tell Us About You!"></textarea>
      <a href="#" id="cmdsend">Send</a>
    </div></div>
  <!-- Popup Div Ends Here -->
</div>

<input id="bookedr" type="hidden" value="">
<input id="bookedc" type="hidden" value="">
<textarea id="myText">
  Welcome to Careerbuilder's Mock Interview Day! </br>
  Your mock interview is set for :
</textarea>



<% end %>
</html>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
    <head>
      <% content_for :head do %>
          <% page_heading "Atlanta / About" %>
          <meta name="description" content="The Atlanta community is invited to CareerBuilder Mock Interview Day. Participants
                                        will have the opportunity to practice their interview skills and receive personalized
                                        feedback from experienced hiring managers." />
          <meta name="robots" content="index, follow" />
      <% end %>

        <div id="header">
            <h4>Next Mock Interview Day: September 17, 2016</h4>
        </div>
      <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Day", class:"respimg")%>
    </head>
    <body>
        <section>
          <h2>About CareerBuilder</h2>
          <br>
            <p class="body_text">CareerBuilder has the largest online job site in the U.S., but we're more than just a job board. We
              are the global leader in human capital solutions. Through constant innovation, unparalleled technology,
              and customer care delivered at every touch point, CareerBuilder helps match the right talent with the
              right opportunity more often than any other site.
            <br><br>
              Our mission is to empower employment. We are striving to organize all the world's human capital
              data and make it meaningful for society.
            </p>
            <br><br>
          <address>
            <strong>For More Information Email</strong><br>
             <a href="mailto:cbmid@cb.com">cbmid@cb.com</a>
          </address>
        </section>
    </body>

</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <% content_for :head do %>
    <% page_heading "Atlanta" %>
    <meta name="description" content="The Atlanta community is invited to CareerBuilder Mock Interview Day. Participants
                                    will have the opportunity to practice their interview skills and receive personalized
                                    feedback from experienced hiring managers." />
  <% end %>
<style>
section {
    width:60%;
    float:left;
    padding:70px;
    font-size: 20px
}
button {
   background-color: #FF3300;
   color:white;
}
aside {
    width:40%;
    float:right;
    padding:70px;
    font-size: 20px
}
footer {
    background-color:#1F1F99;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;
}
    </style>

    <div id="header">
<h4>Next Mock Interview Day: September 17, 2016</h4>
  </div>

  <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Day", class:"respimg")%>
  <%=image_tag("mockphotos.jpg", alt: "CareerBuilder Mock Interview Day", class:"respimg")%>

<body>
<!--<h3 style="color: darkred">NOTE: The registration portal is not yet live, but will be available in the coming weeks. Please check back 3-4 weeks
  in advance to schedule your time</h3>-->
<section>

<h3>CareerBuilder Mock Interview Day will be held on:</h3>

<br>

<strong><font color=#0029A3>Saturday, September 17, 2016 from 9am to 1pm.</font></strong></p>


<address>
  <strong>Location</strong><br>
  CareerBuilder
  5550-A Peachtree Pkwy.<br>
  Norcross, GA 30092<br>
</address>

<h4>Cost: <strong>FREE</strong></h4>

  <p class="body_text">Job seekers in the Atlanta area are invited to practice their interview skills and receive feedback
    from experienced hiring managers. This is not an interview for employment at CareerBuilder, rather an opportunity
    for participants to gauge how well they answer questions in an interview setting, learn interview best practices,
    and get personalized tips on how to improve their interviewing skills. </br></br>

    The mock interview should last about 30 minutes. Participants will do a mock interview for 10-15 minutes followed
    by a 10-15 minute critique by their mock interviewers. At the end of the mock interview, participants will be sent
    home with a personalized feedback worksheet and top interview tips.  

    You can also bring your resume in for an audit.  CareerBuilder hiring managers will review your resume and provide recommendations on how you can make your resume stand out above the rest.
    </br></br>

    Space is limited to the first 100 participants. Cost is FREE. Reservations must be
    made through the registration portal below.
  </p>
  <br>
  <a class="btn btn-warning" href="/schedule" role="button">Schedule a Mock Interview</a>
<br>
<br>
<br>
<address>
  <strong>For More Information Email</strong><br>
  <a href="mailto:cbmid@cb.com">cbmid@cb.com</a>
</address>
</section>

<aside>
  <div style="background-color:#F7F6F3; color:black; padding:20px;">
    <h3>About CareerBuilder</h3>
<br>
<p class="body_text">CareerBuilder has the largest online job site in the U.S., but we're more than just a job board. We
  are the global leader in human capital solutions. Through constant innovation, unparalleled technology,
  and customer care delivered at every touch point, CareerBuilder helps match the right talent with the
  right opportunity more often than any other site.</p>
<br>

</div>
</aside>

</body>

app/views/welcome/schedule.html.erb
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type='text/javascript' src="form.js.erb"></script>
  <link href="../stylesheets/popupform.css" rel="stylesheet">
  <style>
      /*section {
          width:100%;
          float:left;
          padding:70px;
          font-size: 20px
      }*/
      /*button {
         background-color: #FF3300;
         color:white;
      }*/
      /*aside {
          width:40%;
          float:right;
          padding:70px;
          font-size: 20px
      }*/
      /*footer {
          background-color:#1F1F99;
          color:white;
          clear:both;
          text-align:center;
          padding:5px;
      }*/
  </style>
  <div>
    <div id="header">
      <h4>Next Mock Interview Day: September 17, 2016</h4>
    </div>
    <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Day", class:"respimg")%>
        <body>
        <section>
          <h2>Schedule Your Mock Interview Here</h2>

          <br>
          <%= render 'interviews/new' %>
          <br>
          <p>Job seekers in the Atlanta area are invited to practice their interview skills and receive feedback 
          from experienced hiring managers. This is not an interview for employment at CareerBuilder, rather an opportunity
          for participants to gauge how well they answer questions in an interview setting, learn interview best practices, 
          and get personalized tips on how to improve their interviewing skills. <br />
          
          The mock interview should last about 30 minutes. Participants will do a mock interview for 10-15 minutes followed
          by a 10-15 minute critique by their mock interviewers. At the end of the mock interview, participants will be sent
          home with a personalized feedback worksheet and top interview tips. <br />
          
          Space is limited to the first 100 participants. Cost is FREE. Reservations must be made through the registration
          portal here: </p>
          
          <br>
          <br>
          <address>
            <strong>For More Information Email</strong><br>
            <a href="mailto:#">cbmid@cb.com</a>
          </address>
        </section>


        </body>