config/routes.rb
Rails.application.routes.draw do
  resources :user_mailer_autos, :user

  resources :interviews do
    resources :interview_slots
  end

  root 'welcome#index'
  get 'welcome/index'
  get 'index' => 'welcome#index'
  get 'welcome/register'
  get 'register' => 'welcome#register'
  get 'welcome/about'
  get 'about' => 'welcome#about'
  get 'welcome/schedule'
  get 'schedule' => 'interviews#new'
  post 'welcome/schedule' => 'welcome#schedule'
  post 'interviews/new' => 'interviews#create'

  get 'show' => 'interviews#show'
  get 'interview/cancel' => 'interviews#cancel'
  post 'interview/cancel' => 'interviews#cancel'
  resources :interview_slots

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  attr_accessor( :interview_slots )
  attr_accessor( :interviews )
  def index

  end

  def new
    @user = User.new

  end

  private
  def interview_parameters
    params.require(:interview).permit(:name, :lastName, :email, :phoneNumber, :interviewTime, :interviewField,
                                      :interviewStatus, :slotTimeDescription, :slotID)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<html>
<% content_for :head do %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% page_heading "Atlanta / Schedule a Mock Interview" %>
    <meta name="description" content="Hey Atlanta, come participate in CareerBuilder’s Mock Interview Day.  Space is limited.  Register here." />
<% end %>
<div>
  <div id="header">
    <h4>Next Mock Interview Day: August 22, 2015</h4>
  </div>
  <%=image_tag("mockmasthead.jpg", alt: "CareerBuilder Mock Interview Daya", class:"respimg")%>
</div>

	<h2>Cancel Your Mock Interview Here</h2>
	<%= form_for :user, url: new_user_path do |f| %>
    <%= f.text_field :name, :id => 'first_Name', :placeholder =>'Name'  %>
    <%= f.text_field :lastName, :id => 'last_Name', :placeholder =>'Last Name' %>
    <%= f.text_field :email, :id => 'email', :placeholder =>'Email' %>
    <%= f.text_field :phoneNumber, :id => 'phoneNumber',:placeholder =>'Phone Number'  %>
    <%= f.submit 'Submit', :id=> 'cancelForm' %>
  <% end %>
</html>

app/views/user/user.html.erb
Hello!!