config/routes.rb
Rails.application.routes.draw do
  resources :user_mailer_autos, :user

  resources :interviews do
    resources :interview_slots
  end

  root 'welcome#index'
  get 'welcome/index'
  get 'index' => 'welcome#index'
  get 'welcome/register'
  get 'register' => 'welcome#register'
  get 'welcome/about'
  get 'about' => 'welcome#about'
  get 'welcome/schedule'
  get 'schedule' => 'interviews#new'
  post 'welcome/schedule' => 'welcome#schedule'
  post 'interviews/new' => 'interviews#create'

  get 'show' => 'interviews#show'
  get 'interview/cancel' => 'interviews#cancel'
  post 'interview/cancel' => 'interviews#cancel'
  resources :interview_slots

end

app/models/user_mailer_auto.rb
class UserMailerAuto < ActiveRecord::Base
end

app/controllers/user_mailer_autos_controller.rb
class UserMailerAutosController < ApplicationController
  before_action :set_user_mailer_auto, only: [:show, :edit, :update, :destroy]

  # GET /user_mailer_autos
  # GET /user_mailer_autos.json
  def index
    @user_mailer_autos = UserMailerAuto.all
  end

  # GET /user_mailer_autos/1
  # GET /user_mailer_autos/1.json
  def show
  end

  # GET /user_mailer_autos/new
  def new
    @user_mailer_auto = UserMailerAuto.new
  end

  # GET /user_mailer_autos/1/edit
  def edit
  end

  # POST /user_mailer_autos
  # POST /user_mailer_autos.json
  def create
    @user_mailer_auto = UserMailerAuto.new(user_mailer_auto_params)

    respond_to do |format|
      if @user_mailer_auto.save
        format.html { redirect_to @user_mailer_auto, notice: 'User mailer auto was successfully created.' }
        format.json { render :show, status: :created, location: @user_mailer_auto }
      else
        format.html { render :new }
        format.json { render json: @user_mailer_auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_mailer_autos/1
  # PATCH/PUT /user_mailer_autos/1.json
  def update
    respond_to do |format|
      if @user_mailer_auto.update(user_mailer_auto_params)
        format.html { redirect_to @user_mailer_auto, notice: 'User mailer auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_mailer_auto }
      else
        format.html { render :edit }
        format.json { render json: @user_mailer_auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_mailer_autos/1
  # DELETE /user_mailer_autos/1.json
  def destroy
    @user_mailer_auto.destroy
    respond_to do |format|
      format.html { redirect_to user_mailer_autos_url, notice: 'User mailer auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_mailer_auto
      @user_mailer_auto = UserMailerAuto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_mailer_auto_params
      params[:user_mailer_auto]
    end
end

app/helpers/user_mailer_autos_helper.rb
module UserMailerAutosHelper
end

app/views/user_mailer_autos/_form.html.erb
<%= form_for(@user_mailer_auto) do |f| %>
  <% if @user_mailer_auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_mailer_auto.errors.count, "error") %> prohibited this user_mailer_auto from being saved:</h2>

      <ul>
      <% @user_mailer_auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_mailer_autos/edit.html.erb
<h1>Editing User Mailer Auto</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_mailer_auto %> |
<%= link_to 'Back', user_mailer_autos_path %>

app/views/user_mailer_autos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Mailer Autos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_mailer_autos.each do |user_mailer_auto| %>
      <tr>
        <td><%= link_to 'Show', user_mailer_auto %></td>
        <td><%= link_to 'Edit', edit_user_mailer_auto_path(user_mailer_auto) %></td>
        <td><%= link_to 'Destroy', user_mailer_auto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User mailer auto', new_user_mailer_auto_path %>

app/views/user_mailer_autos/new.html.erb
<h1>New User Mailer Auto</h1>

<%= render 'form' %>

<%= link_to 'Back', user_mailer_autos_path %>

app/views/user_mailer_autos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_mailer_auto_path(@user_mailer_auto) %> |
<%= link_to 'Back', user_mailer_autos_path %>